#运行版本
spring:
  profiles:
    active: dev
  flyway:
    baseline-on-migrate: true
#端口
server:
  port: 8088

#分页插件
#pagehelper.helperDialect=mysql
#pagehelper.reasonable=true
pagehelper:
  helperDialect: mysql
  reasonable: true
#  supportMethodsArguments: true
#  params: "count=countSql"


